function pcom = pcom_planar(in1,in2)
%PCOM_PLANAR
%    PCOM = PCOM_PLANAR(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    03-Jan-2026 16:24:34

c1 = in2(4,:);
c2 = in2(5,:);
c3 = in2(6,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(9,:);
m2 = in2(10,:);
m3 = in2(11,:);
phib = in1(3,:);
q1 = in1(4,:);
q2 = in1(5,:);
q3 = in1(6,:);
xb = in1(1,:);
zb = in1(2,:);
t2 = cos(phib);
t3 = cos(q1);
t4 = cos(q2);
t5 = cos(q3);
t6 = sin(phib);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t11 = m1+m2+m3;
t13 = -zb;
t10 = l1.*t3;
t12 = l1.*t7;
t14 = t3.*t4;
t15 = t3.*t8;
t16 = t4.*t7;
t17 = t7.*t8;
t26 = 1.0./t11;
t18 = c2.*t14;
t19 = l2.*t14;
t20 = c2.*t15;
t21 = c2.*t16;
t22 = l2.*t15;
t23 = l2.*t16;
t24 = c2.*t17;
t25 = l2.*t17;
t27 = -t17;
t30 = t15+t16;
t28 = -t24;
t29 = -t25;
t31 = t14+t27;
t32 = c3.*t5.*t30;
t33 = c3.*t9.*t30;
t34 = t12+t20+t21;
t35 = c3.*t5.*t31;
t36 = c3.*t9.*t31;
t37 = -t33;
t38 = t10+t18+t28;
t39 = t12+t22+t23+t32+t36;
t40 = t10+t19+t29+t35+t37;
pcom = [t26.*(m2.*(xb+t2.*t38-t6.*t34)+m3.*(xb+t2.*t40-t6.*t39)+m1.*(xb+c1.*t2.*t3-c1.*t6.*t7));0.0;-t26.*(m2.*(t13+t2.*t34+t6.*t38)+m3.*(t13+t2.*t39+t6.*t40)+m1.*(t13+c1.*t2.*t7+c1.*t3.*t6))];
end
